################
version: '2.1'

services:
  api:
    container_name: api
    build:
      context: ./services/api
    volumes:
      - "./util:/util/"
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      - ES=${ES}
      - SWAGGER_HOST=${SWAGGER_HOST}
